#激活哪一个环境的配置文件
# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：  
#   开发环境：java -jar lapm_task-0.0.1-SNAPSHOT.war --spring.profiles.active=dev  
spring:
  profiles:
    active: dev





#公共配置
server:
  port: 7001





---
# 开发环境配置
spring:
  profiles: dev
  application:
    name: dubbo-trace-web-manage
  dubbo:
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
logging:
  config: classpath:log4j2-dev.xml





---
# 生产环境配置
spring:
  profiles: prod
  application:
    name: dubbo-trace-web-manage
  dubbo:
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
logging:
  config: classpath:log4j2-prod.xml
